-- server/schema.sql — INDEX ONLY.
--
-- The backend was split into four domain-focused D1 databases (see
-- docs/superpowers/plans/2026-06-24-d1-sharding-kv-cache.md). There is no longer
-- a single combined schema. The per-database reference schemas live in:
--
--   server/schema/heap_core.sql       -> DB_HEAP      (heap_base, heap, heap_parameters)
--   server/schema/heap_scores.sql     -> DB_SCORES    (score)
--   server/schema/heap_rewards.sql    -> DB_REWARDS   (reward_codes, code_redemptions)
--   server/schema/heap_telemetry.sql  -> DB_TELEMETRY (logs, feedback)
--
-- Applies are driven by the per-DB migrations under server/migrations/<db>/.
-- The legacy single-DB migrations (0001-0009) are preserved under
-- server/migrations/_legacy_heap/ for the historical `heap` database, which is
-- retired only after the one-time data move (see the sharding runbook).
