name = "heap-server"
main = "src/index.ts"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "heap"
database_id = "2806bb3d-bd95-4780-ae16-ee479eacede9"
