// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
// Re-run the script after adding or removing sprites from src/sprites/Heap_sprites/.

// Vite resolves each ?url import to the correct asset path in dev and production.

import url_0 from '../sprites/Heap_sprites/Individual_items/allow-wheel.png?url';
import url_1 from '../sprites/Heap_sprites/Individual_items/bw-motor-pedal-bike.png?url';
import url_2 from '../sprites/Heap_sprites/Individual_items/car-tire.png?url';
import url_3 from '../sprites/Heap_sprites/Individual_items/chaise2.png?url';
import url_4 from '../sprites/Heap_sprites/Individual_items/classic-car-wheel.png?url';
import url_5 from '../sprites/Heap_sprites/Individual_items/downhill-bike.png?url';
import url_6 from '../sprites/Heap_sprites/Individual_items/dresser.png?url';
import url_7 from '../sprites/Heap_sprites/Individual_items/helmet_v01.png?url';
import url_8 from '../sprites/Heap_sprites/Individual_items/helmet_v02.png?url';
import url_9 from '../sprites/Heap_sprites/Individual_items/helmet_v03.png?url';
import url_10 from '../sprites/Heap_sprites/Individual_items/johnny-automatic-shovel.png?url';
import url_11 from '../sprites/Heap_sprites/Individual_items/lcd-tv.png?url';
import url_12 from '../sprites/Heap_sprites/Individual_items/microwave.png?url';
import url_13 from '../sprites/Heap_sprites/Individual_items/monster-truck.png?url';
import url_14 from '../sprites/Heap_sprites/Individual_items/motorcycle.png?url';
import url_15 from '../sprites/Heap_sprites/Individual_items/mountain-bike.png?url';
import url_16 from '../sprites/Heap_sprites/Individual_items/old-car-engine.png?url';
import url_17 from '../sprites/Heap_sprites/Individual_items/oven.png?url';
import url_18 from '../sprites/Heap_sprites/Individual_items/rfc1394-single-bed.png?url';
import url_19 from '../sprites/Heap_sprites/Individual_items/rg1024-door.png?url';
import url_20 from '../sprites/Heap_sprites/Individual_items/simple-microwave-oven-3d.png?url';
import url_21 from '../sprites/Heap_sprites/Individual_items/sled-coloured.png?url';
import url_22 from '../sprites/Heap_sprites/Individual_items/sled1.png?url';
import url_23 from '../sprites/Heap_sprites/Individual_items/stove-old.png?url';
import url_24 from '../sprites/Heap_sprites/Individual_items/television-old.png?url';
import url_25 from '../sprites/Heap_sprites/Individual_items/tools-shovel.png?url';
import url_26 from '../sprites/Heap_sprites/Individual_items/washing-machine.png?url';
import url_27 from '../sprites/Heap_sprites/Boxes/obj_box001.png?url';
import url_28 from '../sprites/Heap_sprites/Boxes/obj_box002.png?url';
import url_29 from '../sprites/Heap_sprites/Boxes/obj_box003.png?url';
import url_30 from '../sprites/Heap_sprites/Boxes/obj_box004.png?url';
import url_31 from '../sprites/Heap_sprites/Boxes/obj_box005.png?url';
import url_32 from '../sprites/Heap_sprites/Boxes/obj_crate001.png?url';
import url_33 from '../sprites/Heap_sprites/Boxes/obj_crate002.png?url';
import url_34 from '../sprites/Heap_sprites/Boxes/obj_crate003.png?url';
import url_35 from '../sprites/Heap_sprites/Boxes/obj_crate004.png?url';
import url_36 from '../sprites/Heap_sprites/Boxes/obj_crate005.png?url';
import url_37 from '../sprites/Heap_sprites/recycle_items/recycle_items_00.png?url';
import url_38 from '../sprites/Heap_sprites/recycle_items/recycle_items_01.png?url';
import url_39 from '../sprites/Heap_sprites/recycle_items/recycle_items_02.png?url';
import url_40 from '../sprites/Heap_sprites/recycle_items/recycle_items_03.png?url';
import url_41 from '../sprites/Heap_sprites/recycle_items/recycle_items_04.png?url';
import url_42 from '../sprites/Heap_sprites/recycle_items/recycle_items_05.png?url';
import url_43 from '../sprites/Heap_sprites/recycle_items/recycle_items_06.png?url';
import url_44 from '../sprites/Heap_sprites/recycle_items/recycle_items_07.png?url';
import url_45 from '../sprites/Heap_sprites/recycle_items/recycle_items_08.png?url';
import url_46 from '../sprites/Heap_sprites/recycle_items/recycle_items_09.png?url';
import url_47 from '../sprites/Heap_sprites/recycle_items/recycle_items_10.png?url';
import url_48 from '../sprites/Heap_sprites/recycle_items/recycle_items_11.png?url';
import url_49 from '../sprites/Heap_sprites/recycle_items/recycle_items_12.png?url';
import url_50 from '../sprites/Heap_sprites/recycle_items/recycle_items_13.png?url';
import url_51 from '../sprites/Heap_sprites/recycle_items/recycle_items_14.png?url';
import url_52 from '../sprites/Heap_sprites/recycle_items/recycle_items_15.png?url';
import url_53 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_01.png?url';
import url_54 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_02.png?url';
import url_55 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_03.png?url';
import url_56 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_04.png?url';
import url_57 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_05.png?url';
import url_58 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_06.png?url';
import url_59 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_07.png?url';
import url_60 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_08.png?url';
import url_61 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_09.png?url';
import url_62 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_10.png?url';
import url_63 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_100.png?url';
import url_64 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_101.png?url';
import url_65 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_102.png?url';
import url_66 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_103.png?url';
import url_67 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_104.png?url';
import url_68 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_105.png?url';
import url_69 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_106.png?url';
import url_70 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_107.png?url';
import url_71 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_108.png?url';
import url_72 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_109.png?url';
import url_73 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_11.png?url';
import url_74 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_110.png?url';
import url_75 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_111.png?url';
import url_76 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_112.png?url';
import url_77 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_113.png?url';
import url_78 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_114.png?url';
import url_79 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_115.png?url';
import url_80 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_116.png?url';
import url_81 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_117.png?url';
import url_82 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_118.png?url';
import url_83 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_119.png?url';
import url_84 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_12.png?url';
import url_85 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_120.png?url';
import url_86 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_121.png?url';
import url_87 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_122.png?url';
import url_88 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_123.png?url';
import url_89 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_124.png?url';
import url_90 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_125.png?url';
import url_91 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_126.png?url';
import url_92 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_127.png?url';
import url_93 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_128.png?url';
import url_94 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_129.png?url';
import url_95 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_13.png?url';
import url_96 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_130.png?url';
import url_97 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_131.png?url';
import url_98 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_132.png?url';
import url_99 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_133.png?url';
import url_100 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_134.png?url';
import url_101 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_135.png?url';
import url_102 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_136.png?url';
import url_103 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_137.png?url';
import url_104 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_138.png?url';
import url_105 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_139.png?url';
import url_106 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_14.png?url';
import url_107 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_140.png?url';
import url_108 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_141.png?url';
import url_109 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_142.png?url';
import url_110 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_143.png?url';
import url_111 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_144.png?url';
import url_112 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_145.png?url';
import url_113 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_146.png?url';
import url_114 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_147.png?url';
import url_115 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_148.png?url';
import url_116 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_149.png?url';
import url_117 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_15.png?url';
import url_118 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_150.png?url';
import url_119 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_151.png?url';
import url_120 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_152.png?url';
import url_121 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_153.png?url';
import url_122 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_154.png?url';
import url_123 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_155.png?url';
import url_124 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_156.png?url';
import url_125 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_157.png?url';
import url_126 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_158.png?url';
import url_127 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_159.png?url';
import url_128 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_16.png?url';
import url_129 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_160.png?url';
import url_130 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_161.png?url';
import url_131 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_162.png?url';
import url_132 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_163.png?url';
import url_133 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_164.png?url';
import url_134 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_165.png?url';
import url_135 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_166.png?url';
import url_136 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_167.png?url';
import url_137 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_168.png?url';
import url_138 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_169.png?url';
import url_139 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_17.png?url';
import url_140 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_170.png?url';
import url_141 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_171.png?url';
import url_142 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_172.png?url';
import url_143 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_173.png?url';
import url_144 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_174.png?url';
import url_145 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_175.png?url';
import url_146 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_176.png?url';
import url_147 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_177.png?url';
import url_148 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_178.png?url';
import url_149 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_179.png?url';
import url_150 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_18.png?url';
import url_151 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_180.png?url';
import url_152 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_181.png?url';
import url_153 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_182.png?url';
import url_154 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_183.png?url';
import url_155 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_184.png?url';
import url_156 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_185.png?url';
import url_157 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_186.png?url';
import url_158 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_187.png?url';
import url_159 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_188.png?url';
import url_160 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_189.png?url';
import url_161 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_19.png?url';
import url_162 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_190.png?url';
import url_163 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_191.png?url';
import url_164 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_192.png?url';
import url_165 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_193.png?url';
import url_166 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_194.png?url';
import url_167 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_195.png?url';
import url_168 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_196.png?url';
import url_169 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_197.png?url';
import url_170 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_198.png?url';
import url_171 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_199.png?url';
import url_172 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_20.png?url';
import url_173 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_200.png?url';
import url_174 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_201.png?url';
import url_175 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_202.png?url';
import url_176 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_203.png?url';
import url_177 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_204.png?url';
import url_178 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_205.png?url';
import url_179 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_206.png?url';
import url_180 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_207.png?url';
import url_181 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_208.png?url';
import url_182 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_209.png?url';
import url_183 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_21.png?url';
import url_184 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_210.png?url';
import url_185 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_211.png?url';
import url_186 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_212.png?url';
import url_187 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_213.png?url';
import url_188 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_214.png?url';
import url_189 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_215.png?url';
import url_190 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_216.png?url';
import url_191 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_217.png?url';
import url_192 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_218.png?url';
import url_193 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_219.png?url';
import url_194 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_22.png?url';
import url_195 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_220.png?url';
import url_196 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_221.png?url';
import url_197 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_222.png?url';
import url_198 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_223.png?url';
import url_199 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_224.png?url';
import url_200 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_225.png?url';
import url_201 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_226.png?url';
import url_202 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_227.png?url';
import url_203 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_228.png?url';
import url_204 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_229.png?url';
import url_205 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_23.png?url';
import url_206 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_230.png?url';
import url_207 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_231.png?url';
import url_208 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_232.png?url';
import url_209 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_233.png?url';
import url_210 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_234.png?url';
import url_211 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_235.png?url';
import url_212 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_236.png?url';
import url_213 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_237.png?url';
import url_214 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_238.png?url';
import url_215 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_239.png?url';
import url_216 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_24.png?url';
import url_217 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_240.png?url';
import url_218 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_241.png?url';
import url_219 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_242.png?url';
import url_220 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_243.png?url';
import url_221 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_244.png?url';
import url_222 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_245.png?url';
import url_223 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_246.png?url';
import url_224 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_247.png?url';
import url_225 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_248.png?url';
import url_226 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_249.png?url';
import url_227 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_25.png?url';
import url_228 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_250.png?url';
import url_229 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_251.png?url';
import url_230 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_252.png?url';
import url_231 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_253.png?url';
import url_232 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_254.png?url';
import url_233 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_255.png?url';
import url_234 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_256.png?url';
import url_235 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_257.png?url';
import url_236 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_258.png?url';
import url_237 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_259.png?url';
import url_238 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_26.png?url';
import url_239 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_260.png?url';
import url_240 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_261.png?url';
import url_241 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_262.png?url';
import url_242 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_263.png?url';
import url_243 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_264.png?url';
import url_244 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_265.png?url';
import url_245 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_266.png?url';
import url_246 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_267.png?url';
import url_247 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_268.png?url';
import url_248 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_269.png?url';
import url_249 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_27.png?url';
import url_250 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_270.png?url';
import url_251 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_271.png?url';
import url_252 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_272.png?url';
import url_253 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_273.png?url';
import url_254 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_274.png?url';
import url_255 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_275.png?url';
import url_256 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_276.png?url';
import url_257 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_277.png?url';
import url_258 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_278.png?url';
import url_259 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_279.png?url';
import url_260 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_28.png?url';
import url_261 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_280.png?url';
import url_262 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_281.png?url';
import url_263 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_282.png?url';
import url_264 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_283.png?url';
import url_265 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_29.png?url';
import url_266 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_30.png?url';
import url_267 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_31.png?url';
import url_268 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_32.png?url';
import url_269 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_33.png?url';
import url_270 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_34.png?url';
import url_271 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_35.png?url';
import url_272 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_36.png?url';
import url_273 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_37.png?url';
import url_274 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_38.png?url';
import url_275 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_39.png?url';
import url_276 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_40.png?url';
import url_277 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_41.png?url';
import url_278 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_42.png?url';
import url_279 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_43.png?url';
import url_280 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_44.png?url';
import url_281 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_45.png?url';
import url_282 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_46.png?url';
import url_283 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_47.png?url';
import url_284 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_48.png?url';
import url_285 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_49.png?url';
import url_286 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_50.png?url';
import url_287 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_51.png?url';
import url_288 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_52.png?url';
import url_289 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_53.png?url';
import url_290 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_54.png?url';
import url_291 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_55.png?url';
import url_292 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_56.png?url';
import url_293 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_57.png?url';
import url_294 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_58.png?url';
import url_295 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_59.png?url';
import url_296 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_60.png?url';
import url_297 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_61.png?url';
import url_298 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_62.png?url';
import url_299 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_63.png?url';
import url_300 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_64.png?url';
import url_301 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_65.png?url';
import url_302 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_66.png?url';
import url_303 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_67.png?url';
import url_304 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_68.png?url';
import url_305 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_69.png?url';
import url_306 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_70.png?url';
import url_307 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_71.png?url';
import url_308 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_72.png?url';
import url_309 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_73.png?url';
import url_310 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_74.png?url';
import url_311 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_75.png?url';
import url_312 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_76.png?url';
import url_313 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_77.png?url';
import url_314 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_78.png?url';
import url_315 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_79.png?url';
import url_316 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_80.png?url';
import url_317 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_81.png?url';
import url_318 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_82.png?url';
import url_319 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_83.png?url';
import url_320 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_84.png?url';
import url_321 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_85.png?url';
import url_322 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_86.png?url';
import url_323 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_87.png?url';
import url_324 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_88.png?url';
import url_325 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_89.png?url';
import url_326 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_90.png?url';
import url_327 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_91.png?url';
import url_328 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_92.png?url';
import url_329 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_93.png?url';
import url_330 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_94.png?url';
import url_331 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_95.png?url';
import url_332 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_96.png?url';
import url_333 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_97.png?url';
import url_334 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_98.png?url';
import url_335 from '../sprites/Heap_sprites/russiancars_pack1_side/russiancars_pack1_side_99.png?url';

/** Maps textureKey → resolved asset URL. Used by BootScene to load sprites. */
export const HEAP_PNG_URLS: Record<string, string> = {
  'allow-wheel': url_0,
  'bw-motor-pedal-bike': url_1,
  'car-tire': url_2,
  'chaise2': url_3,
  'classic-car-wheel': url_4,
  'downhill-bike': url_5,
  'dresser': url_6,
  'helmet-v01': url_7,
  'helmet-v02': url_8,
  'helmet-v03': url_9,
  'johnny-automatic-shovel': url_10,
  'lcd-tv': url_11,
  'microwave': url_12,
  'monster-truck': url_13,
  'motorcycle': url_14,
  'mountain-bike': url_15,
  'old-car-engine': url_16,
  'oven': url_17,
  'rfc1394-single-bed': url_18,
  'rg1024-door': url_19,
  'simple-microwave-oven-3d': url_20,
  'sled-coloured': url_21,
  'sled1': url_22,
  'stove-old': url_23,
  'television-old': url_24,
  'tools-shovel': url_25,
  'washing-machine': url_26,
  'obj-box001': url_27,
  'obj-box002': url_28,
  'obj-box003': url_29,
  'obj-box004': url_30,
  'obj-box005': url_31,
  'obj-crate001': url_32,
  'obj-crate002': url_33,
  'obj-crate003': url_34,
  'obj-crate004': url_35,
  'obj-crate005': url_36,
  'recycle-items-00': url_37,
  'recycle-items-01': url_38,
  'recycle-items-02': url_39,
  'recycle-items-03': url_40,
  'recycle-items-04': url_41,
  'recycle-items-05': url_42,
  'recycle-items-06': url_43,
  'recycle-items-07': url_44,
  'recycle-items-08': url_45,
  'recycle-items-09': url_46,
  'recycle-items-10': url_47,
  'recycle-items-11': url_48,
  'recycle-items-12': url_49,
  'recycle-items-13': url_50,
  'recycle-items-14': url_51,
  'recycle-items-15': url_52,
  'russiancars-pack1-side-01': url_53,
  'russiancars-pack1-side-02': url_54,
  'russiancars-pack1-side-03': url_55,
  'russiancars-pack1-side-04': url_56,
  'russiancars-pack1-side-05': url_57,
  'russiancars-pack1-side-06': url_58,
  'russiancars-pack1-side-07': url_59,
  'russiancars-pack1-side-08': url_60,
  'russiancars-pack1-side-09': url_61,
  'russiancars-pack1-side-10': url_62,
  'russiancars-pack1-side-100': url_63,
  'russiancars-pack1-side-101': url_64,
  'russiancars-pack1-side-102': url_65,
  'russiancars-pack1-side-103': url_66,
  'russiancars-pack1-side-104': url_67,
  'russiancars-pack1-side-105': url_68,
  'russiancars-pack1-side-106': url_69,
  'russiancars-pack1-side-107': url_70,
  'russiancars-pack1-side-108': url_71,
  'russiancars-pack1-side-109': url_72,
  'russiancars-pack1-side-11': url_73,
  'russiancars-pack1-side-110': url_74,
  'russiancars-pack1-side-111': url_75,
  'russiancars-pack1-side-112': url_76,
  'russiancars-pack1-side-113': url_77,
  'russiancars-pack1-side-114': url_78,
  'russiancars-pack1-side-115': url_79,
  'russiancars-pack1-side-116': url_80,
  'russiancars-pack1-side-117': url_81,
  'russiancars-pack1-side-118': url_82,
  'russiancars-pack1-side-119': url_83,
  'russiancars-pack1-side-12': url_84,
  'russiancars-pack1-side-120': url_85,
  'russiancars-pack1-side-121': url_86,
  'russiancars-pack1-side-122': url_87,
  'russiancars-pack1-side-123': url_88,
  'russiancars-pack1-side-124': url_89,
  'russiancars-pack1-side-125': url_90,
  'russiancars-pack1-side-126': url_91,
  'russiancars-pack1-side-127': url_92,
  'russiancars-pack1-side-128': url_93,
  'russiancars-pack1-side-129': url_94,
  'russiancars-pack1-side-13': url_95,
  'russiancars-pack1-side-130': url_96,
  'russiancars-pack1-side-131': url_97,
  'russiancars-pack1-side-132': url_98,
  'russiancars-pack1-side-133': url_99,
  'russiancars-pack1-side-134': url_100,
  'russiancars-pack1-side-135': url_101,
  'russiancars-pack1-side-136': url_102,
  'russiancars-pack1-side-137': url_103,
  'russiancars-pack1-side-138': url_104,
  'russiancars-pack1-side-139': url_105,
  'russiancars-pack1-side-14': url_106,
  'russiancars-pack1-side-140': url_107,
  'russiancars-pack1-side-141': url_108,
  'russiancars-pack1-side-142': url_109,
  'russiancars-pack1-side-143': url_110,
  'russiancars-pack1-side-144': url_111,
  'russiancars-pack1-side-145': url_112,
  'russiancars-pack1-side-146': url_113,
  'russiancars-pack1-side-147': url_114,
  'russiancars-pack1-side-148': url_115,
  'russiancars-pack1-side-149': url_116,
  'russiancars-pack1-side-15': url_117,
  'russiancars-pack1-side-150': url_118,
  'russiancars-pack1-side-151': url_119,
  'russiancars-pack1-side-152': url_120,
  'russiancars-pack1-side-153': url_121,
  'russiancars-pack1-side-154': url_122,
  'russiancars-pack1-side-155': url_123,
  'russiancars-pack1-side-156': url_124,
  'russiancars-pack1-side-157': url_125,
  'russiancars-pack1-side-158': url_126,
  'russiancars-pack1-side-159': url_127,
  'russiancars-pack1-side-16': url_128,
  'russiancars-pack1-side-160': url_129,
  'russiancars-pack1-side-161': url_130,
  'russiancars-pack1-side-162': url_131,
  'russiancars-pack1-side-163': url_132,
  'russiancars-pack1-side-164': url_133,
  'russiancars-pack1-side-165': url_134,
  'russiancars-pack1-side-166': url_135,
  'russiancars-pack1-side-167': url_136,
  'russiancars-pack1-side-168': url_137,
  'russiancars-pack1-side-169': url_138,
  'russiancars-pack1-side-17': url_139,
  'russiancars-pack1-side-170': url_140,
  'russiancars-pack1-side-171': url_141,
  'russiancars-pack1-side-172': url_142,
  'russiancars-pack1-side-173': url_143,
  'russiancars-pack1-side-174': url_144,
  'russiancars-pack1-side-175': url_145,
  'russiancars-pack1-side-176': url_146,
  'russiancars-pack1-side-177': url_147,
  'russiancars-pack1-side-178': url_148,
  'russiancars-pack1-side-179': url_149,
  'russiancars-pack1-side-18': url_150,
  'russiancars-pack1-side-180': url_151,
  'russiancars-pack1-side-181': url_152,
  'russiancars-pack1-side-182': url_153,
  'russiancars-pack1-side-183': url_154,
  'russiancars-pack1-side-184': url_155,
  'russiancars-pack1-side-185': url_156,
  'russiancars-pack1-side-186': url_157,
  'russiancars-pack1-side-187': url_158,
  'russiancars-pack1-side-188': url_159,
  'russiancars-pack1-side-189': url_160,
  'russiancars-pack1-side-19': url_161,
  'russiancars-pack1-side-190': url_162,
  'russiancars-pack1-side-191': url_163,
  'russiancars-pack1-side-192': url_164,
  'russiancars-pack1-side-193': url_165,
  'russiancars-pack1-side-194': url_166,
  'russiancars-pack1-side-195': url_167,
  'russiancars-pack1-side-196': url_168,
  'russiancars-pack1-side-197': url_169,
  'russiancars-pack1-side-198': url_170,
  'russiancars-pack1-side-199': url_171,
  'russiancars-pack1-side-20': url_172,
  'russiancars-pack1-side-200': url_173,
  'russiancars-pack1-side-201': url_174,
  'russiancars-pack1-side-202': url_175,
  'russiancars-pack1-side-203': url_176,
  'russiancars-pack1-side-204': url_177,
  'russiancars-pack1-side-205': url_178,
  'russiancars-pack1-side-206': url_179,
  'russiancars-pack1-side-207': url_180,
  'russiancars-pack1-side-208': url_181,
  'russiancars-pack1-side-209': url_182,
  'russiancars-pack1-side-21': url_183,
  'russiancars-pack1-side-210': url_184,
  'russiancars-pack1-side-211': url_185,
  'russiancars-pack1-side-212': url_186,
  'russiancars-pack1-side-213': url_187,
  'russiancars-pack1-side-214': url_188,
  'russiancars-pack1-side-215': url_189,
  'russiancars-pack1-side-216': url_190,
  'russiancars-pack1-side-217': url_191,
  'russiancars-pack1-side-218': url_192,
  'russiancars-pack1-side-219': url_193,
  'russiancars-pack1-side-22': url_194,
  'russiancars-pack1-side-220': url_195,
  'russiancars-pack1-side-221': url_196,
  'russiancars-pack1-side-222': url_197,
  'russiancars-pack1-side-223': url_198,
  'russiancars-pack1-side-224': url_199,
  'russiancars-pack1-side-225': url_200,
  'russiancars-pack1-side-226': url_201,
  'russiancars-pack1-side-227': url_202,
  'russiancars-pack1-side-228': url_203,
  'russiancars-pack1-side-229': url_204,
  'russiancars-pack1-side-23': url_205,
  'russiancars-pack1-side-230': url_206,
  'russiancars-pack1-side-231': url_207,
  'russiancars-pack1-side-232': url_208,
  'russiancars-pack1-side-233': url_209,
  'russiancars-pack1-side-234': url_210,
  'russiancars-pack1-side-235': url_211,
  'russiancars-pack1-side-236': url_212,
  'russiancars-pack1-side-237': url_213,
  'russiancars-pack1-side-238': url_214,
  'russiancars-pack1-side-239': url_215,
  'russiancars-pack1-side-24': url_216,
  'russiancars-pack1-side-240': url_217,
  'russiancars-pack1-side-241': url_218,
  'russiancars-pack1-side-242': url_219,
  'russiancars-pack1-side-243': url_220,
  'russiancars-pack1-side-244': url_221,
  'russiancars-pack1-side-245': url_222,
  'russiancars-pack1-side-246': url_223,
  'russiancars-pack1-side-247': url_224,
  'russiancars-pack1-side-248': url_225,
  'russiancars-pack1-side-249': url_226,
  'russiancars-pack1-side-25': url_227,
  'russiancars-pack1-side-250': url_228,
  'russiancars-pack1-side-251': url_229,
  'russiancars-pack1-side-252': url_230,
  'russiancars-pack1-side-253': url_231,
  'russiancars-pack1-side-254': url_232,
  'russiancars-pack1-side-255': url_233,
  'russiancars-pack1-side-256': url_234,
  'russiancars-pack1-side-257': url_235,
  'russiancars-pack1-side-258': url_236,
  'russiancars-pack1-side-259': url_237,
  'russiancars-pack1-side-26': url_238,
  'russiancars-pack1-side-260': url_239,
  'russiancars-pack1-side-261': url_240,
  'russiancars-pack1-side-262': url_241,
  'russiancars-pack1-side-263': url_242,
  'russiancars-pack1-side-264': url_243,
  'russiancars-pack1-side-265': url_244,
  'russiancars-pack1-side-266': url_245,
  'russiancars-pack1-side-267': url_246,
  'russiancars-pack1-side-268': url_247,
  'russiancars-pack1-side-269': url_248,
  'russiancars-pack1-side-27': url_249,
  'russiancars-pack1-side-270': url_250,
  'russiancars-pack1-side-271': url_251,
  'russiancars-pack1-side-272': url_252,
  'russiancars-pack1-side-273': url_253,
  'russiancars-pack1-side-274': url_254,
  'russiancars-pack1-side-275': url_255,
  'russiancars-pack1-side-276': url_256,
  'russiancars-pack1-side-277': url_257,
  'russiancars-pack1-side-278': url_258,
  'russiancars-pack1-side-279': url_259,
  'russiancars-pack1-side-28': url_260,
  'russiancars-pack1-side-280': url_261,
  'russiancars-pack1-side-281': url_262,
  'russiancars-pack1-side-282': url_263,
  'russiancars-pack1-side-283': url_264,
  'russiancars-pack1-side-29': url_265,
  'russiancars-pack1-side-30': url_266,
  'russiancars-pack1-side-31': url_267,
  'russiancars-pack1-side-32': url_268,
  'russiancars-pack1-side-33': url_269,
  'russiancars-pack1-side-34': url_270,
  'russiancars-pack1-side-35': url_271,
  'russiancars-pack1-side-36': url_272,
  'russiancars-pack1-side-37': url_273,
  'russiancars-pack1-side-38': url_274,
  'russiancars-pack1-side-39': url_275,
  'russiancars-pack1-side-40': url_276,
  'russiancars-pack1-side-41': url_277,
  'russiancars-pack1-side-42': url_278,
  'russiancars-pack1-side-43': url_279,
  'russiancars-pack1-side-44': url_280,
  'russiancars-pack1-side-45': url_281,
  'russiancars-pack1-side-46': url_282,
  'russiancars-pack1-side-47': url_283,
  'russiancars-pack1-side-48': url_284,
  'russiancars-pack1-side-49': url_285,
  'russiancars-pack1-side-50': url_286,
  'russiancars-pack1-side-51': url_287,
  'russiancars-pack1-side-52': url_288,
  'russiancars-pack1-side-53': url_289,
  'russiancars-pack1-side-54': url_290,
  'russiancars-pack1-side-55': url_291,
  'russiancars-pack1-side-56': url_292,
  'russiancars-pack1-side-57': url_293,
  'russiancars-pack1-side-58': url_294,
  'russiancars-pack1-side-59': url_295,
  'russiancars-pack1-side-60': url_296,
  'russiancars-pack1-side-61': url_297,
  'russiancars-pack1-side-62': url_298,
  'russiancars-pack1-side-63': url_299,
  'russiancars-pack1-side-64': url_300,
  'russiancars-pack1-side-65': url_301,
  'russiancars-pack1-side-66': url_302,
  'russiancars-pack1-side-67': url_303,
  'russiancars-pack1-side-68': url_304,
  'russiancars-pack1-side-69': url_305,
  'russiancars-pack1-side-70': url_306,
  'russiancars-pack1-side-71': url_307,
  'russiancars-pack1-side-72': url_308,
  'russiancars-pack1-side-73': url_309,
  'russiancars-pack1-side-74': url_310,
  'russiancars-pack1-side-75': url_311,
  'russiancars-pack1-side-76': url_312,
  'russiancars-pack1-side-77': url_313,
  'russiancars-pack1-side-78': url_314,
  'russiancars-pack1-side-79': url_315,
  'russiancars-pack1-side-80': url_316,
  'russiancars-pack1-side-81': url_317,
  'russiancars-pack1-side-82': url_318,
  'russiancars-pack1-side-83': url_319,
  'russiancars-pack1-side-84': url_320,
  'russiancars-pack1-side-85': url_321,
  'russiancars-pack1-side-86': url_322,
  'russiancars-pack1-side-87': url_323,
  'russiancars-pack1-side-88': url_324,
  'russiancars-pack1-side-89': url_325,
  'russiancars-pack1-side-90': url_326,
  'russiancars-pack1-side-91': url_327,
  'russiancars-pack1-side-92': url_328,
  'russiancars-pack1-side-93': url_329,
  'russiancars-pack1-side-94': url_330,
  'russiancars-pack1-side-95': url_331,
  'russiancars-pack1-side-96': url_332,
  'russiancars-pack1-side-97': url_333,
  'russiancars-pack1-side-98': url_334,
  'russiancars-pack1-side-99': url_335,
};
