// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
// Re-run the script after adding or removing sprites from src/sprites/.

// Vite resolves each ?url import to the correct asset path in dev and production.
// Explicit per-file imports avoid glob key-normalisation issues.

import url_0 from '../sprites/allow-wheel.png?url';
import url_1 from '../sprites/bw-motor-pedal-bike.png?url';
import url_2 from '../sprites/car-tire.png?url';
import url_3 from '../sprites/chaise2.png?url';
import url_4 from '../sprites/classic-car-wheel.png?url';
import url_5 from '../sprites/downhill-bike.png?url';
import url_6 from '../sprites/dresser.png?url';
import url_7 from '../sprites/johnny-automatic-shovel.png?url';
import url_8 from '../sprites/lcd-tv.png?url';
import url_9 from '../sprites/microwave.png?url';
import url_10 from '../sprites/monster-truck.png?url';
import url_11 from '../sprites/motorcycle.png?url';
import url_12 from '../sprites/mountain-bike.png?url';
import url_13 from '../sprites/old-car-engine.png?url';
import url_14 from '../sprites/oven.png?url';
import url_15 from '../sprites/rfc1394-single-bed.png?url';
import url_16 from '../sprites/rg1024-door.png?url';
import url_17 from '../sprites/road-bike.png?url';
import url_18 from '../sprites/simple-microwave-oven-3d.png?url';
import url_19 from '../sprites/sled-coloured.png?url';
import url_20 from '../sprites/sled1.png?url';
import url_21 from '../sprites/stove-old.png?url';
import url_22 from '../sprites/television-old.png?url';
import url_23 from '../sprites/tools-shovel.png?url';
import url_24 from '../sprites/washing-machine.png?url';

/** Maps textureKey → resolved asset URL. Used by BootScene to load sprites. */
export const HEAP_PNG_URLS: Record<string, string> = {
  'allow-wheel': url_0,
  'bw-motor-pedal-bike': url_1,
  'car-tire': url_2,
  'chaise2': url_3,
  'classic-car-wheel': url_4,
  'downhill-bike': url_5,
  'dresser': url_6,
  'johnny-automatic-shovel': url_7,
  'lcd-tv': url_8,
  'microwave': url_9,
  'monster-truck': url_10,
  'motorcycle': url_11,
  'mountain-bike': url_12,
  'old-car-engine': url_13,
  'oven': url_14,
  'rfc1394-single-bed': url_15,
  'rg1024-door': url_16,
  'road-bike': url_17,
  'simple-microwave-oven-3d': url_18,
  'sled-coloured': url_19,
  'sled1': url_20,
  'stove-old': url_21,
  'television-old': url_22,
  'tools-shovel': url_23,
  'washing-machine': url_24,
};
