// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
// Re-run the script after adding or removing SVGs.

import { ObjectDef } from './heapTypes';

/**
 * Maps keyid → object definition.
 * textureKey must match the key used in BootScene when loading the SVG.
 * width/height are scaled game-pixels (longest side = 96px).
 */
export const OBJECT_DEFS: Record<number, ObjectDef> = {
  0: { textureKey: 'allow-wheel', filename: 'Allow-wheel.svg', width: 69, height: 96 }, // Allow-wheel.svg
  1: { textureKey: 'car-tire', filename: 'Car-Tire.svg', width: 61, height: 96 }, // Car-Tire.svg
  2: { textureKey: 'chaise2', filename: 'Chaise2.svg', width: 96, height: 61 }, // Chaise2.svg
  3: { textureKey: 'dresser', filename: 'Dresser.svg', width: 80, height: 96 }, // Dresser.svg
  4: { textureKey: 'lcd-tv', filename: 'LCD-TV.svg', width: 96, height: 68 }, // LCD-TV.svg
  5: { textureKey: 'oven', filename: 'Oven.svg', width: 72, height: 96 }, // Oven.svg
  6: { textureKey: 'rfc1394-single-bed', filename: 'Rfc1394-Single-Bed.svg', width: 96, height: 54 }, // Rfc1394-Single-Bed.svg
  7: { textureKey: 'stove-old', filename: 'Stove-old.svg', width: 76, height: 96 }, // Stove-old.svg
  8: { textureKey: 'television-old', filename: 'Television-OLD.svg', width: 96, height: 67 }, // Television-OLD.svg
  9: { textureKey: 'bw-motor-pedal-bike', filename: 'bw-motor-pedal-bike.svg', width: 96, height: 79 }, // bw-motor-pedal-bike.svg
  10: { textureKey: 'classic-car-wheel', filename: 'classic-car-wheel.svg', width: 96, height: 96 }, // classic-car-wheel.svg
  11: { textureKey: 'downhill-bike', filename: 'downhill-bike.svg', width: 96, height: 66 }, // downhill-bike.svg
  12: { textureKey: 'johnny-automatic-shovel', filename: 'johnny-automatic-shovel.svg', width: 15, height: 96 }, // johnny-automatic-shovel.svg
  13: { textureKey: 'microwave', filename: 'microwave.svg', width: 96, height: 96 }, // microwave.svg
  14: { textureKey: 'monster-truck', filename: 'monster-truck.svg', width: 96, height: 57 }, // monster-truck.svg
  15: { textureKey: 'motorcycle', filename: 'motorcycle.svg', width: 96, height: 51 }, // motorcycle.svg
  16: { textureKey: 'mountain-bike', filename: 'mountain-bike.svg', width: 96, height: 56 }, // mountain-bike.svg
  17: { textureKey: 'old-car-engine', filename: 'old-car-engine.svg', width: 96, height: 93 }, // old-car-engine.svg
  18: { textureKey: 'rg1024-door', filename: 'rg1024-Door.svg', width: 71, height: 96 }, // rg1024-Door.svg
  19: { textureKey: 'road-bike', filename: 'road-bike.svg', width: 96, height: 59 }, // road-bike.svg
  20: { textureKey: 'simple-microwave-oven-3d', filename: 'simple-microwave-oven-3d.svg', width: 96, height: 58 }, // simple-microwave-oven-3d.svg
  21: { textureKey: 'sled-coloured', filename: 'sled-coloured.svg', width: 96, height: 57 }, // sled-coloured.svg
  22: { textureKey: 'sled1', filename: 'sled1.svg', width: 96, height: 74 }, // sled1.svg
  23: { textureKey: 'tools-shovel', filename: 'tools-shovel.svg', width: 96, height: 92 }, // tools-shovel.svg
  24: { textureKey: 'washing-machine', filename: 'washing-machine.svg', width: 96, height: 96 }, // washing-machine.svg
};

/** Convenience array ordered by keyid. */
export const OBJECT_DEF_LIST = Object.values(OBJECT_DEFS);

export const HEAP_ITEM_COUNT = 25;
