// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
// Re-run the script after adding or removing SVGs.

// Vite resolves each ?url import to the correct asset path in dev and production.
// Explicit per-file imports avoid glob key-normalisation issues with spaces in filenames.

import url_0 from '../svgs/Allow-wheel.svg?url';
import url_1 from '../svgs/Car-Tire.svg?url';
import url_2 from '../svgs/Chaise2.svg?url';
import url_3 from '../svgs/Dresser.svg?url';
import url_4 from '../svgs/LCD-TV.svg?url';
import url_5 from '../svgs/Oven.svg?url';
import url_6 from '../svgs/Rfc1394-Single-Bed.svg?url';
import url_7 from '../svgs/Stove-old.svg?url';
import url_8 from '../svgs/Television-OLD.svg?url';
import url_9 from '../svgs/bw-motor-pedal-bike.svg?url';
import url_10 from '../svgs/classic-car-wheel.svg?url';
import url_11 from '../svgs/downhill-bike.svg?url';
import url_12 from '../svgs/johnny-automatic-shovel.svg?url';
import url_13 from '../svgs/microwave.svg?url';
import url_14 from '../svgs/monster-truck.svg?url';
import url_15 from '../svgs/motorcycle.svg?url';
import url_16 from '../svgs/mountain-bike.svg?url';
import url_17 from '../svgs/old-car-engine.svg?url';
import url_18 from '../svgs/rg1024-Door.svg?url';
import url_19 from '../svgs/road-bike.svg?url';
import url_20 from '../svgs/simple-microwave-oven-3d.svg?url';
import url_21 from '../svgs/sled-coloured.svg?url';
import url_22 from '../svgs/sled1.svg?url';
import url_23 from '../svgs/tools-shovel.svg?url';
import url_24 from '../svgs/washing-machine.svg?url';

/** Maps textureKey → resolved asset URL. Used by BootScene to load SVGs. */
export const HEAP_SVG_URLS: Record<string, string> = {
  'allow-wheel': url_0,
  'car-tire': url_1,
  'chaise2': url_2,
  'dresser': url_3,
  'lcd-tv': url_4,
  'oven': url_5,
  'rfc1394-single-bed': url_6,
  'stove-old': url_7,
  'television-old': url_8,
  'bw-motor-pedal-bike': url_9,
  'classic-car-wheel': url_10,
  'downhill-bike': url_11,
  'johnny-automatic-shovel': url_12,
  'microwave': url_13,
  'monster-truck': url_14,
  'motorcycle': url_15,
  'mountain-bike': url_16,
  'old-car-engine': url_17,
  'rg1024-door': url_18,
  'road-bike': url_19,
  'simple-microwave-oven-3d': url_20,
  'sled-coloured': url_21,
  'sled1': url_22,
  'tools-shovel': url_23,
  'washing-machine': url_24,
};
