// AUTO-GENERATED by scripts/gen-heap-texture.mjs — do not edit by hand.
// Re-run the script after changing TILE_COUNT in sprite-config.mjs.

import tile0Url from '../assets/composite-heap-0.png?url';
import tile1Url from '../assets/composite-heap-1.png?url';
import tile2Url from '../assets/composite-heap-2.png?url';
import tile3Url from '../assets/composite-heap-3.png?url';

export const HEAP_TILE_COUNT = 4;

/** Resolved asset URLs for all heap tiles, indexed 0…HEAP_TILE_COUNT-1. */
export const HEAP_TILE_URLS: string[] = [
  tile0Url,
  tile1Url,
  tile2Url,
  tile3Url,
];
