// Re-exports from the auto-generated definitions file.
// Add new items by dropping SVGs in src/svgs/ and running: node scripts/gen-heap-defs.mjs
export { OBJECT_DEFS, OBJECT_DEF_LIST, HEAP_ITEM_COUNT } from './heapItemDefs';

// Heapitemdefs is auto generate using the below script, which reads the SVG files in src/svgs/ and creates entries with their dimensions. The textureKey is derived from the filename (without extension) and must match the key used in BootScene when loading the SVGs.
// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
//
// To regenerate (e.g. after adding new SVGs to src/svgs/):
//   1. Drop the new .svg files into src/svgs/
//   2. From the project root, run:
//        node scripts/gen-heap-defs.mjs
//   3. This file will be overwritten with updated entries.