// AUTO-GENERATED by scripts/gen-heap-defs.mjs — do not edit by hand.
// Re-run the script after adding or removing sprites from src/sprites/.

import { ObjectDef } from './heapTypes';

/**
 * Maps keyid → object definition.
 * textureKey must match the key used in BootScene when loading the PNG.
 * width/height are the actual PNG dimensions in game pixels.
 */
export const OBJECT_DEFS: Record<number, ObjectDef> = {
  0: { textureKey: 'allow-wheel', filename: 'allow-wheel.png', width: 69, height: 96 }, // allow-wheel.png
  1: { textureKey: 'bw-motor-pedal-bike', filename: 'bw-motor-pedal-bike.png', width: 96, height: 79 }, // bw-motor-pedal-bike.png
  2: { textureKey: 'car-tire', filename: 'car-tire.png', width: 61, height: 96 }, // car-tire.png
  3: { textureKey: 'chaise2', filename: 'chaise2.png', width: 96, height: 61 }, // chaise2.png
  4: { textureKey: 'classic-car-wheel', filename: 'classic-car-wheel.png', width: 96, height: 96 }, // classic-car-wheel.png
  5: { textureKey: 'downhill-bike', filename: 'downhill-bike.png', width: 96, height: 66 }, // downhill-bike.png
  6: { textureKey: 'dresser', filename: 'dresser.png', width: 80, height: 96 }, // dresser.png
  7: { textureKey: 'johnny-automatic-shovel', filename: 'johnny-automatic-shovel.png', width: 15, height: 96 }, // johnny-automatic-shovel.png
  8: { textureKey: 'lcd-tv', filename: 'lcd-tv.png', width: 96, height: 68 }, // lcd-tv.png
  9: { textureKey: 'microwave', filename: 'microwave.png', width: 96, height: 96 }, // microwave.png
  10: { textureKey: 'monster-truck', filename: 'monster-truck.png', width: 96, height: 57 }, // monster-truck.png
  11: { textureKey: 'motorcycle', filename: 'motorcycle.png', width: 96, height: 51 }, // motorcycle.png
  12: { textureKey: 'mountain-bike', filename: 'mountain-bike.png', width: 96, height: 56 }, // mountain-bike.png
  13: { textureKey: 'old-car-engine', filename: 'old-car-engine.png', width: 96, height: 93 }, // old-car-engine.png
  14: { textureKey: 'oven', filename: 'oven.png', width: 72, height: 96 }, // oven.png
  15: { textureKey: 'rfc1394-single-bed', filename: 'rfc1394-single-bed.png', width: 96, height: 54 }, // rfc1394-single-bed.png
  16: { textureKey: 'rg1024-door', filename: 'rg1024-door.png', width: 71, height: 96 }, // rg1024-door.png
  17: { textureKey: 'road-bike', filename: 'road-bike.png', width: 96, height: 59 }, // road-bike.png
  18: { textureKey: 'simple-microwave-oven-3d', filename: 'simple-microwave-oven-3d.png', width: 96, height: 58 }, // simple-microwave-oven-3d.png
  19: { textureKey: 'sled-coloured', filename: 'sled-coloured.png', width: 96, height: 57 }, // sled-coloured.png
  20: { textureKey: 'sled1', filename: 'sled1.png', width: 96, height: 74 }, // sled1.png
  21: { textureKey: 'stove-old', filename: 'stove-old.png', width: 76, height: 96 }, // stove-old.png
  22: { textureKey: 'television-old', filename: 'television-old.png', width: 96, height: 67 }, // television-old.png
  23: { textureKey: 'tools-shovel', filename: 'tools-shovel.png', width: 96, height: 92 }, // tools-shovel.png
  24: { textureKey: 'washing-machine', filename: 'washing-machine.png', width: 96, height: 96 }, // washing-machine.png
};

/** Convenience array ordered by keyid. */
export const OBJECT_DEF_LIST = Object.values(OBJECT_DEFS);

export const HEAP_ITEM_COUNT = 25;
